### ISSUE TITLE
cannot get MVS TK4- to work with wc3270 

### ISSUE THREAD

**Issue by mrbillknight** [moshix/mvs#4]
I have TK4- installed and it looks like it is working.
I have wc3270 installed and it looks like it is working.

I start TK4- and get all expected messages, I can issue commands and they work.
I start wc3270 and I see a message in TK4- that it has connected,

As I understand I do not need to do anything else with TK-4

From wc3270 I can see the TK4- logo and can use the ‘file’ ‘options’ and ‘Keypad’ functions

I do not get the ‘logon’ message

I have tried everything I can think of for the past 3 days with no success
I have looked for anyone that can help, but no luck there either

Can you get me past this step so I can continue my process of running cobol programs on  my win 10 desktop,

Thank you in advance for answering my request.

**Comment by mrbillknight** [comment]
20:21:18 HHC01413I Hercules version 4.00
20:21:18 HHC01414I (c) Copyright 1999-2012 by Roger Bowler, Jan Jaeger, and others
20:21:18 HHC01415I Built on Jun 26 2016 at 22:04:26
20:21:18 HHC01416I Build information:
20:21:18 HHC01417I Windows (MSVC) build for AMD64
20:21:18 HHC01417I Hercules for TK4- (64-bit Windows)
20:21:18 HHC01417I Modes: S/370 ESA/390 z/Arch
20:21:18 HHC01417I Max CPU Engines: 8
20:21:18 HHC01417I Using   fthreads Threading Model
20:21:18 HHC01417I Using   Error-Checking Mutex Locking Model
20:21:18 HHC01417I Using   FishIO
20:21:18 HHC01417I With    Dynamic loading support
20:21:18 HHC01417I Using   shared libraries
20:21:18 HHC01417I With    External GUI support
20:21:18 HHC01417I With    IPV6 support
20:21:18 HHC01417I With    HTTP Server support
20:21:18 HHC01417I With    sqrtl support
20:21:18 HHC01417I Without SIGABEND handler
20:21:18 HHC01417I With    CCKD BZIP2 support
20:21:18 HHC01417I With    HET BZIP2 support
20:21:18 HHC01417I With    ZLIB support
20:21:18 HHC01417I With    Regular Expressions support
20:21:18 HHC01417I Without Object REXX support
20:21:18 HHC01417I Without Regina REXX support
20:21:18 HHC01417I With    Automatic Operator support
20:21:18 HHC01417I Without National Language Support
20:21:18 HHC01417I Machine dependent assists: cmpxchg1 cmpxchg4 cmpxchg8
20:21:18 HHC01417I Running on BILLLS-DESKTOP Windows-6.2.9200.  unknown 64-bit, AMD(R) x64 LP=16, Cores=8, CPUs=1
20:21:18 HHC00100I Thread id 00004138, prio 15, name Processor CP00 started
20:21:18 HHC00100I Thread id 00006328, prio -20, name Timer started
20:21:18 HHC00811I Processor CP00: architecture mode z/Arch
20:21:18 HHC01802I HTTP server using root directory C:/MVS/hercules/httproot/
20:21:18 HHC01807I HTTP server signaled to start
20:21:18 HHC00100I Thread id 00003FE8, prio  0, name HTTP server started
20:21:18 HHC01802I HTTP server using root directory C:/MVS/hercules/httproot/
20:21:18 HHC01803I HTTP server waiting for requests on port 8038
20:21:18 HHC01042I 0:000C COMM: device bound to socket 3505
20:21:18 HHC00100I Thread id 00000614, prio  0, name Socket device listener started
20:21:18 HHC01437I Config file[45] conf/tk4-.cnf: including file conf/extcons.cnf
20:21:18 HHC00100I Thread id 00002A2C, prio  0, name Console connection started
20:21:18 HHC01024I Waiting for console connections on port 3270
20:21:18 HHC01437I Config file[71] conf/tk4-.cnf: including file conf/tk4-_default.cnf
20:21:19 HHC00971I 0:0610 CTC: connect to 127.0.0.1:18610 failed, starting server
20:21:20 HHC00971I 0:0611 CTC: connect to 127.0.0.1:18611 failed, starting server
20:21:20 HHC00100I Thread id 00005B1C, prio  0, name 3705 device(1:0660) thread started
20:21:20 HHC01004I 0:0660 COMM: listening on port 37051 for incoming TCP connections
20:21:20 HHC00100I Thread id 00005778, prio  0, name 3705 device(1:0661) thread started
20:21:20 HHC01004I 0:0661 COMM: listening on port 37052 for incoming TCP connections
20:21:20 HHC00100I Thread id 000063C8, prio  0, name 3705 device(1:0662) thread started
20:21:20 HHC01004I 0:0662 COMM: listening on port 37053 for incoming TCP connections
20:21:20 HHC00100I Thread id 000047CC, prio  0, name 3705 device(1:0663) thread started
20:21:20 HHC01004I 0:0663 COMM: listening on port 37054 for incoming TCP connections
20:21:20 HHC00100I Thread id 000005D4, prio  0, name 3705 device(1:0664) thread started
20:21:20 HHC01004I 0:0664 COMM: listening on port 37055 for incoming TCP connections
20:21:20 HHC00100I Thread id 00000DDC, prio  0, name 3705 device(1:0665) thread started
20:21:20 HHC01004I 0:0665 COMM: listening on port 37056 for incoming TCP connections
20:21:20 HHC00100I Thread id 000066CC, prio  0, name 3705 device(1:0666) thread started
20:21:20 HHC01004I 0:0666 COMM: listening on port 37057 for incoming TCP connections
20:21:20 HHC01004I 0:0667 COMM: listening on port 37058 for incoming TCP connections
20:21:20 HHC00100I Thread id 00006AF8, prio  0, name 3705 device(1:0667) thread started
20:21:20 HHC00100I Thread id 00006910, prio  0, name 3705 device(1:0668) thread started
20:21:20 HHC01004I 0:0668 COMM: listening on port 37911 for incoming TCP connections
20:21:20 HHC01004I 0:0669 COMM: listening on port 37912 for incoming TCP connections
20:21:20 HHC00100I Thread id 00001334, prio  0, name 3705 device(1:0669) thread started
20:21:20 HHC00100I Thread id 000061A8, prio  0, name 3705 device(1:066A) thread started
20:21:20 HHC01004I 0:066A COMM: listening on port 37913 for incoming TCP connections
20:21:20 HHC00100I Thread id 000005F4, prio  0, name 3705 device(1:066B) thread started
20:21:20 HHC01004I 0:066B COMM: listening on port 37914 for incoming TCP connections
20:21:20 HHC00100I Thread id 000038D0, prio  0, name 0:0670 communication thread started
20:21:20 HHC01004I 0:0670 COMM: listening on port 37801 for incoming TCP connections
20:21:20 HHC00100I Thread id 00006984, prio  0, name 0:0671 communication thread started
20:21:20 HHC01004I 0:0671 COMM: listening on port 37802 for incoming TCP connections
20:21:20 HHC00100I Thread id 00006B0C, prio  0, name 0:0672 communication thread started
20:21:20 HHC01004I 0:0672 COMM: listening on port 37803 for incoming TCP connections
20:21:20 HHC00100I Thread id 0000544C, prio  0, name 0:0673 communication thread started
20:21:20 HHC01004I 0:0673 COMM: listening on port 37804 for incoming TCP connections
20:21:20 HHC00100I Thread id 00003A64, prio  0, name 0:0680 communication thread started
20:21:20 HHC01004I 0:0680 COMM: listening on port 33351 for incoming TCP connections
20:21:20 HHC00100I Thread id 000063E8, prio  0, name 0:0681 communication thread started
20:21:20 HHC01004I 0:0681 COMM: listening on port 33352 for incoming TCP connections
20:21:20 HHC00100I Thread id 00005888, prio  0, name 0:0682 communication thread started
20:21:20 HHC01004I 0:0682 COMM: listening on port 33353 for incoming TCP connections
20:21:20 HHC00100I Thread id 000029EC, prio  0, name 0:0683 communication thread started
20:21:20 HHC01004I 0:0683 COMM: listening on port 33354 for incoming TCP connections
20:21:20 HHC00100I Thread id 000031FC, prio  0, name 0:0688 communication thread started
20:21:20 HHC01004I 0:0688 COMM: listening on port 27411 for incoming TCP connections
20:21:20 HHC00100I Thread id 000062B8, prio  0, name 0:0689 communication thread started
20:21:20 HHC01004I 0:0689 COMM: listening on port 27412 for incoming TCP connections
20:21:20 HHC00100I Thread id 00006920, prio  0, name 0:068A communication thread started
20:21:20 HHC01004I 0:068A COMM: listening on port 27413 for incoming TCP connections
20:21:20 HHC00100I Thread id 00004FAC, prio  0, name 0:068B communication thread started
20:21:20 HHC01004I 0:068B COMM: listening on port 27414 for incoming TCP connections
20:21:20 HHC00100I Thread id 00005548, prio  0, name 0:068C communication thread started
20:21:20 HHC01004I 0:068C COMM: listening on port 27415 for incoming TCP connections
20:21:20 HHC00100I Thread id 00000A14, prio  0, name 0:068D communication thread started
20:21:20 HHC01004I 0:068D COMM: listening on port 27416 for incoming TCP connections
20:21:20 HHC00100I Thread id 00006060, prio  0, name 0:068E communication thread started
20:21:20 HHC01004I 0:068E COMM: listening on port 27417 for incoming TCP connections
20:21:20 HHC00100I Thread id 00006A94, prio  0, name 0:068F communication thread started
20:21:20 HHC01004I 0:068F COMM: listening on port 27418 for incoming TCP connections
20:21:20 HHC00414I 0:0152 CKD file dasd/hasp00.152: cyls 411 heads 19 tracks 7809 trklen 13312
20:21:20 HHC00414I 0:0191 CKD file dasd/mvscat.191: cyls 1114 heads 15 tracks 16710 trklen 56832
20:21:20 HHC00414I 0:0248 CKD file dasd/mvsdlb.248: cyls 560 heads 30 tracks 16800 trklen 19456
20:21:20 HHC00414I 0:0148 CKD file dasd/mvsres.148: cyls 560 heads 30 tracks 16800 trklen 19456
20:21:20 HHC00414I 0:0160 CKD file dasd/page00.160: cyls 698 heads 12 tracks 8376 trklen 8704
20:21:20 HHC00414I 0:0161 CKD file dasd/page01.161: cyls 698 heads 12 tracks 8376 trklen 8704
20:21:20 HHC00414I 0:0240 CKD file dasd/pub000.240: cyls 560 heads 30 tracks 16800 trklen 19456
20:21:20 HHC00414I 0:0241 CKD file dasd/pub010.241: cyls 560 heads 30 tracks 16800 trklen 19456
20:21:20 HHC00414I 0:0270 CKD file dasd/pub001.270: cyls 960 heads 12 tracks 11520 trklen 35840
20:21:20 HHC00414I 0:0271 CKD file dasd/pub011.271: cyls 960 heads 12 tracks 11520 trklen 35840
20:21:20 HHC00414I 0:0280 CKD file dasd/pub002.280: cyls 1772 heads 15 tracks 26580 trklen 47616
20:21:20 HHC00414I 0:0281 CKD file dasd/pub012.281: cyls 1772 heads 15 tracks 26580 trklen 47616
20:21:20 HHC00414I 0:0290 CKD file dasd/pub003.290: cyls 1114 heads 15 tracks 16710 trklen 56832
20:21:20 HHC00414I 0:0291 CKD file dasd/pub013.291: cyls 2047 heads 15 tracks 30705 trklen 56832
20:21:20 HHC00414I 0:0149 CKD file dasd/smp001.149: cyls 560 heads 30 tracks 16800 trklen 19456
20:21:20 HHC00414I 0:014A CKD file dasd/smp002.14a: cyls 560 heads 30 tracks 16800 trklen 19456
20:21:20 HHC00414I 0:014B CKD file dasd/smp003.14b: cyls 560 heads 30 tracks 16800 trklen 19456
20:21:20 HHC00414I 0:014C CKD file dasd/smp004.14c: cyls 560 heads 30 tracks 16800 trklen 19456
20:21:20 HHC00414I 0:0131 CKD file dasd/sort01.131: cyls 203 heads 20 tracks 4060 trklen 7680
20:21:20 HHC00414I 0:0132 CKD file dasd/sort02.132: cyls 203 heads 20 tracks 4060 trklen 7680
20:21:20 HHC00414I 0:0133 CKD file dasd/sort03.133: cyls 203 heads 20 tracks 4060 trklen 7680
20:21:20 HHC00414I 0:0134 CKD file dasd/sort04.134: cyls 203 heads 20 tracks 4060 trklen 7680
20:21:20 HHC00414I 0:0135 CKD file dasd/sort05.135: cyls 203 heads 20 tracks 4060 trklen 7680
20:21:20 HHC00414I 0:0136 CKD file dasd/sort06.136: cyls 203 heads 20 tracks 4060 trklen 7680
20:21:20 HHC00414I 0:0140 CKD file dasd/work00.140: cyls 560 heads 30 tracks 16800 trklen 19456
20:21:20 HHC00414I 0:0170 CKD file dasd/work01.170: cyls 960 heads 12 tracks 11520 trklen 35840
20:21:20 HHC00414I 0:0180 CKD file dasd/work02.180: cyls 886 heads 15 tracks 13290 trklen 47616
20:21:20 HHC00414I 0:0190 CKD file dasd/work03.190: cyls 1114 heads 15 tracks 16710 trklen 56832
20:21:20 HHC01437I Config file[106] conf/tk4-.cnf: including file conf/cbt_dasd.cnf
20:21:20 HHC01437I Config file[110] conf/tk4-.cnf: including file conf/source_dasd.cnf
20:21:20 HHC01437I Config file[114] conf/tk4-.cnf: including file conf/tk4-_updates.cnf
20:21:20 HHC01437I Config file[10] conf/tk4-.cnf: including file conf/tk4-_updates/01
20:21:20 HHC01437I Config file[11] conf/tk4-.cnf: including file conf/tk4-_updates/02
20:21:20 HHC01437I Config file[12] conf/tk4-.cnf: including file conf/tk4-_updates/03
20:21:20 HHC01437I Config file[13] conf/tk4-.cnf: including file conf/tk4-_updates/04
20:21:20 HHC01437I Config file[14] conf/tk4-.cnf: including file conf/tk4-_updates/05
20:21:20 HHC01437I Config file[15] conf/tk4-.cnf: including file conf/tk4-_updates/06
20:21:20 HHC01437I Config file[16] conf/tk4-.cnf: including file conf/tk4-_updates/07
20:21:20 HHC01437I Config file[17] conf/tk4-.cnf: including file conf/tk4-_updates/08
20:21:20 HHC01437I Config file[18] conf/tk4-.cnf: including file conf/tk4-_updates/09
20:21:20 HHC01437I Config file[19] conf/tk4-.cnf: including file conf/tk4-_updates/10
20:21:20 HHC01437I Config file[118] conf/tk4-.cnf: including file conf/local.cnf
20:21:20 HHC01437I Config file[10] conf/tk4-.cnf: including file local_conf/01
20:21:20 HHC01437I Config file[11] conf/tk4-.cnf: including file local_conf/02
20:21:20 HHC01437I Config file[12] conf/tk4-.cnf: including file local_conf/03
20:21:20 HHC01437I Config file[13] conf/tk4-.cnf: including file local_conf/04
20:21:20 HHC01437I Config file[14] conf/tk4-.cnf: including file local_conf/05
20:21:20 HHC01437I Config file[15] conf/tk4-.cnf: including file local_conf/06
20:21:20 HHC01437I Config file[16] conf/tk4-.cnf: including file local_conf/07
20:21:20 HHC01437I Config file[17] conf/tk4-.cnf: including file local_conf/08
20:21:20 HHC01437I Config file[18] conf/tk4-.cnf: including file local_conf/09
20:21:20 HHC01437I Config file[19] conf/tk4-.cnf: including file local_conf/10
20:21:20 HHC00100I Thread id 00006B44, prio  0, name Control panel started
20:21:20 HHC02260I Script 1: begin processing file scripts/tk4-.rc
20:21:21 HHC01603I script scripts/tk4-_updates.rc
20:21:21 HHC02260I Script 1: begin processing file scripts/tk4-_updates.rc
20:21:21 HHC01603I script scripts/tk4-_updates/01
20:21:21 HHC02260I Script 1: begin processing file scripts/tk4-_updates/01
20:21:21 HHC02264I Script 1: file scripts/tk4-_updates/01 processing ended
20:21:21 HHC01603I script scripts/tk4-_updates/02
20:21:21 HHC02260I Script 1: begin processing file scripts/tk4-_updates/02
20:21:21 HHC02264I Script 1: file scripts/tk4-_updates/02 processing ended
20:21:21 HHC01603I script scripts/tk4-_updates/03
20:21:21 HHC02260I Script 1: begin processing file scripts/tk4-_updates/03
20:21:21 HHC02264I Script 1: file scripts/tk4-_updates/03 processing ended
20:21:21 HHC01603I script scripts/tk4-_updates/04
20:21:21 HHC02260I Script 1: begin processing file scripts/tk4-_updates/04
20:21:21 HHC02264I Script 1: file scripts/tk4-_updates/04 processing ended
20:21:21 HHC01603I script scripts/tk4-_updates/05
20:21:21 HHC02260I Script 1: begin processing file scripts/tk4-_updates/05
20:21:21 HHC02264I Script 1: file scripts/tk4-_updates/05 processing ended
20:21:21 HHC01603I script scripts/tk4-_updates/06
20:21:21 HHC02260I Script 1: begin processing file scripts/tk4-_updates/06
20:21:21 HHC02264I Script 1: file scripts/tk4-_updates/06 processing ended
20:21:21 HHC01603I script scripts/tk4-_updates/07
20:21:21 HHC02260I Script 1: begin processing file scripts/tk4-_updates/07
20:21:21 HHC02264I Script 1: file scripts/tk4-_updates/07 processing ended
20:21:21 HHC01603I script scripts/tk4-_updates/08
20:21:21 HHC02260I Script 1: begin processing file scripts/tk4-_updates/08
20:21:21 HHC02264I Script 1: file scripts/tk4-_updates/08 processing ended
20:21:21 HHC01603I script scripts/tk4-_updates/09
20:21:21 HHC02260I Script 1: begin processing file scripts/tk4-_updates/09
20:21:21 HHC02264I Script 1: file scripts/tk4-_updates/09 processing ended
20:21:21 HHC01603I script scripts/tk4-_updates/10
20:21:21 HHC02260I Script 1: begin processing file scripts/tk4-_updates/10
20:21:21 HHC02264I Script 1: file scripts/tk4-_updates/10 processing ended
20:21:21 HHC02264I Script 1: file scripts/tk4-_updates.rc processing ended
20:21:21 HHC01603I ${LOCALRC:=script scripts/local.rc}
20:21:21 HHC02260I Script 1: begin processing file scripts/local.rc
20:21:21 HHC01603I script local_scripts/01
20:21:21 HHC02260I Script 1: begin processing file local_scripts/01
20:21:21 HHC02264I Script 1: file local_scripts/01 processing ended
20:21:21 HHC01603I script local_scripts/02
20:21:21 HHC02260I Script 1: begin processing file local_scripts/02
20:21:21 HHC02264I Script 1: file local_scripts/02 processing ended
20:21:21 HHC01603I script local_scripts/03
20:21:21 HHC02260I Script 1: begin processing file local_scripts/03
20:21:21 HHC02264I Script 1: file local_scripts/03 processing ended
20:21:21 HHC01603I script local_scripts/04
20:21:21 HHC02260I Script 1: begin processing file local_scripts/04
20:21:21 HHC02264I Script 1: file local_scripts/04 processing ended
20:21:21 HHC01603I script local_scripts/05
20:21:21 HHC02260I Script 1: begin processing file local_scripts/05
20:21:21 HHC02264I Script 1: file local_scripts/05 processing ended
20:21:21 HHC01603I script local_scripts/06
20:21:21 HHC02260I Script 1: begin processing file local_scripts/06
20:21:21 HHC02264I Script 1: file local_scripts/06 processing ended
20:21:21 HHC01603I script local_scripts/07
20:21:21 HHC02260I Script 1: begin processing file local_scripts/07
20:21:21 HHC02264I Script 1: file local_scripts/07 processing ended
20:21:21 HHC01603I script local_scripts/08
20:21:21 HHC02260I Script 1: begin processing file local_scripts/08
20:21:21 HHC02264I Script 1: file local_scripts/08 processing ended
20:21:21 HHC01603I script local_scripts/09
20:21:21 HHC02260I Script 1: begin processing file local_scripts/09
20:21:21 HHC02264I Script 1: file local_scripts/09 processing ended
20:21:21 HHC01603I script local_scripts/10
20:21:21 HHC02260I Script 1: begin processing file local_scripts/10
20:21:21 HHC02264I Script 1: file local_scripts/10 processing ended
20:21:21 HHC02264I Script 1: file scripts/local.rc processing ended
20:21:22 HHC01603I *
20:21:22 HHC01603I *                           ************   ****  *****          ||
20:21:22 HHC01603I *                           **   **   **    **    **           |||
20:21:22 HHC01603I *                           **   **   **    **   **           ||||
20:21:22 HHC01603I *                                **         **  **           || ||
20:21:22 HHC01603I *        |l      _,,,---,,_      **         ** **           ||  ||
20:21:22 HHC01603I * ZZZzz /,'.-'`'    -.  ;-;;,    **         ****           ||   ||
20:21:22 HHC01603I *      |,4-  ) )-,_. ,( (  ''-'  **         *****         ||    ||
20:21:22 HHC01603I *     '---''(_/--'  `-')_)       **         **  **       ||     ||    ||||||||||
20:21:22 HHC01603I *                                **         **   **      |||||||||||  Update 08
20:21:22 HHC01603I *       The MVS 3.8j             **         **    **            ||
20:21:22 HHC01603I *     Tur(n)key System           **         **     **           ||
20:21:22 HHC01603I *                              ******      ****     ***       ||||||
20:21:22 HHC01603I *
20:21:22 HHC01603I *            TK3 created by Volker Bandke       vbandke@bsp-gmbh.com
20:21:22 HHC01603I *            TK4- update by Juergen Winkelmann  winkelmann@id.ethz.ch
20:21:22 HHC01603I *                     see TK4-.CREDITS for complete credits
20:21:22 HHC01603I *
20:21:22 HHC02264I Script 1: file scripts/tk4-.rc processing ended
20:29:08 HHC01018I 0:00C0 COMM: client 192.168.1.119 devtype 3270: connected

**Comment by mrbillknight** [comment]
I can get wc3270 to a command prompt by starting 3270 mode, but when I enter a command it goes into a wait

**Comment by moshix** [comment]
thanks, but this has nothing to do with this repository. I am closing this issue.
