### ISSUE TITLE
sort.jcl ending with MAXCC 16 due to sort capacity is reached.

### ISSUE THREAD

**Issue by shrikant-jawalekar** [moshix/mvs#5]
I executed this job on MVS Hyperian 4.2 version. Do you think this is an installation issue?

https://github.com/moshix/mvs/blob/master/sort.jcl

HERC01S    SORT                SORT      RC= 0016 
IEF404I HERC01S - ENDED - TIME=18.20.02           
$HASP395 HERC01S  ENDED                           

IER036I - B =   90                
IER037I - G =  2424               
IER038I - NMAX = 1663920          
IER046A - SORT CAPACITY EXCEEDED  
IER066A - APROX RCD CNT 1649049

**Comment by marXtevens** [comment]
Remember, you are working in a 16-bit environment, 2^16=65536. It would appear you have, for sort, too many records, 1.6M.

Your other clues include the two error messages.
IER038I - NMAX = 1663920 (which is smaller than) IER066A - APROX RCD CNT 1649049

I Hope This Helps

**Comment by moshix** [comment]
Remember, I am working in a 24bit environment. 2^24 = 16,777,216 blocks (not records). Depending on blocking factor that's many records. 

Remember, banks like Citibank were using 24bit MVS in the days then they had many more than 16 million customers and still could process them. the IRS had many more than 16 million tax payers in the days of their use of MVS 24 bit and still processed them just fine.

**Comment by moshix** [comment]
Remember, I am working in a 24bit environment. 2^24 = 16,777,216 blocks (not records). Depending on blocking factor that's many records. 

Remember, banks like Citibank were using 24bit MVS in the days then they had many more than 16 million customers and still could process them. the IRS had many more than 16 million tax payers in the days of their use of MVS 24 bit and still processed them just fine.

**Comment by moshix** [comment]
Remember, I am working in a 24bit environment, not 16 bit.  
 2^24 = 16,777,216 blocks (not records). Depending on blocking factor that's many records. 

Remember, banks like Citibank were using 24bit MVS in the days then they had many more than 16 million customers and still could process them. the IRS had many more than 16 million tax payers in the days of their use of MVS 24 bit and still processed them just fine.

**Comment by moshix** [comment]
Remember, I am working in a 24bit environment, not 16 bit.  
 2^24 = 16,777,216 blocks (not records). Depending on blocking factor that's many records. 

Remember, banks like Citibank were using 24bit MVS in the days then they had many more than 16 million customers and still could process them. the IRS had many more than 16 million tax payers in the days of their use of MVS 24 bit and still processed them just fine.

**Comment by moshix** [comment]
Remember, I am working in a 24bit environment, not 16 bit.  
 2^24 = 16,777,216 blocks (not records). Depending on blocking factor that's many records. 

Remember, banks like Citibank were using 24bit MVS in the days then they had many more than 16 million customers and still could process them. the IRS had many more than 16 million tax payers in the days of their use of MVS 24 bit and still processed them just fine.

**Comment by moshix** [comment]
Remember, I am working in a 24bit environment, not 16 bit.  
 2^24 = 16,777,216 blocks (not records). Depending on blocking factor that's many records. 

Remember, banks like Citibank were using 24bit MVS in the days then they had many more than 16 million customers and still could process them. the IRS had many more than 16 million tax payers in the days of their use of MVS 24 bit and still processed them just fine.

**Comment by moshix** [comment]
Remember, I am working in a 24bit environment, not 16 bit.  
 2^24 = 16,777,216 blocks (not records). Depending on blocking factor that's many records. 

Remember, banks like Citibank were using 24bit MVS in the days then they had many more than 16 million customers and still could process them. the IRS had many more than 16 million tax payers in the days of their use of MVS 24 bit and still processed them just fine.

**Comment by moshix** [comment]
Remember, I am working in a 24bit environment, not 16 bit.  
 2^24 = 16,777,216 blocks (not records). Depending on blocking factor that's many records. 

Remember, banks like Citibank were using 24bit MVS in the days then they had many more than 16 million customers and still could process them. the IRS had many more than 16 million tax payers in the days of their use of MVS 24 bit and still processed them just fine.

**Comment by moshix** [comment]
Remember, I am working in a 24bit environment, not 16 bit.  
 2^24 = 16,777,216 blocks (not records). Depending on blocking factor that's many records. 

Remember, banks like Citibank were using 24bit MVS in the days then they had many more than 16 million customers and still could process them. the IRS had many more than 16 million tax payers in the days of their use of MVS 24 bit and still processed them just fine.

**Comment by moshix** [comment]
Remember, I am working in a 24bit environment, not 16 bit.  
 2^24 = 16,777,216 blocks (not records). Depending on blocking factor that's many records. 

Remember, banks like Citibank were using 24bit MVS in the days then they had many more than 16 million customers and still could process them. the IRS had many more than 16 million tax payers in the days of their use of MVS 24 bit and still processed them just fine.

**Comment by moshix** [comment]
Remember, I am working in a 24bit environment, not 16 bit.  
 2^24 = 16,777,216 blocks (not records). Depending on blocking factor that's many records. 

Remember, banks like Citibank were using 24bit MVS in the days then they had many more than 16 million customers and still could process them. the IRS had many more than 16 million tax payers in the days of their use of MVS 24 bit and still processed them just fine.

**Comment by moshix** [comment]
Remember, I am working in a 24bit environment, not 16 bit.  
 2^24 = 16,777,216 blocks (not records). Depending on blocking factor that's many records. 

Remember, banks like Citibank were using 24bit MVS in the days then they had many more than 16 million customers and still could process them. the IRS had many more than 16 million tax payers in the days of their use of MVS 24 bit and still processed them just fine.

**Comment by moshix** [comment]
Remember, I am working in a 24bit environment, not 16 bit.  
 2^24 = 16,777,216 blocks (not records). Depending on blocking factor that's many records. 

Remember, banks like Citibank were using 24bit MVS in the days then they had many more than 16 million customers and still could process them. the IRS had many more than 16 million tax payers in the days of their use of MVS 24 bit and still processed them just fine.
