### ISSUE TITLE
In Sept.-Version hercules browser console isn't working any more

### ISSUE THREAD

**Issue by KlausDilper** [moshix/mvs#7]
I always get the message "connection refused" or similar. even if I give full access to the browser. The former version from May still works well.

**Comment by misterspock1** [comment]
> I always get the message "connection refused" or similar. even if I give full access to the browser. The former version from May still works well.

You have to uncomment the line HTTP PORT ${HTTPPORT:=8038}  in conf/tk4-.cnf (Remove the #) and it should work again.

**Comment by KlausDilper** [comment]
Hallo Michael,
sorry, but still getting the message: Connection refused





Greetings,
Klaus
    Am Sonntag, 16. Oktober 2022 um 13:32:21 MESZ hat Michael Richmond ***@***.***> Folgendes geschrieben:  
 
 



I always get the message "connection refused" or similar. even if I give full access to the browser. The former version from May still works well.


You have to uncomment the line HTTP PORT ${HTTPPORT:=8038} in conf/tk4-.cnf (Remove the #) and it should work again.

**Comment by KlausDilper** [comment]
Hi all,

I have now uncommented all tags with HTTP* and now it works again. 

Many thanks

KLaus
